services:
  nginx:
    image: nginx:alpine
    container_name: yomali_nginx
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - yomali_network

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        - XDEBUG_MODE=${XDEBUG_MODE}
        - XDEBUG_CLIENT_HOST=${XDEBUG_CLIENT_HOST}
        - XDEBUG_CLIENT_PORT=${XDEBUG_CLIENT_PORT}
    container_name: yomali_php
    volumes:
      - ./:/var/www
    working_dir: /var/www
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_TEST_NAME=${DB_TEST_NAME}
      - XDEBUG_MODE=${XDEBUG_MODE}
      - XDEBUG_CONFIG=client_host=${XDEBUG_CLIENT_HOST} client_port=${XDEBUG_CLIENT_PORT}
      - PHP_IDE_CONFIG=serverName=yomali-tracker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mysql
    networks:
      - yomali_network

  mysql:
    image: mysql:latest
    container_name: yomali_mysql
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    networks:
      - yomali_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: yomali_phpmyadmin
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT_PASSWORD}
      UPLOAD_LIMIT: 300M
    depends_on:
      - mysql
    networks:
      - yomali_network

networks:
  yomali_network:
    driver: bridge

volumes:
  mysql_data: