openapi: 3.0.0
info:
  title: Yomali Traffic Tracker API
  version: 1.0.0
  description: |
    Professional website traffic tracking system built with PHP 8.4 and clean architecture principles.
    
    ## Base URL
    All API endpoints are relative to: `http://localhost:8888/api/v1/`

servers:
  - url: http://localhost:8888/api/v1
    description: Local development server
  - url: /api/v1
    description: Relative URL for current host

paths:
  /track:
    post:
      tags:
        - Tracking
      summary: Track a page visit
      description: |
        Records a page visit from a website. Automatically detects visitor IP address 
        from request headers (X-Forwarded-For, X-Real-IP, REMOTE_ADDR).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - url
              properties:
                url:
                  type: string
                  format: uri
                  description: The URL of the page being visited
                  example: https://example.com/product/123
            examples:
              website_page:
                summary: Website page
                value:
                  url: "https://example.com/about"
              blog_post:
                summary: Blog post  
                value:
                  url: "https://myblog.com/posts/how-to-track-visitors"
              e_commerce:
                summary: E-commerce product
                value:
                  url: "https://shop.example.com/products/item-456"
      responses:
        '204':
          description: Visit tracked successfully
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                missing_url:
                  summary: Missing URL
                  value:
                    error: "URL is required"
                invalid_json:
                  summary: Invalid JSON
                  value:
                    error: "Invalid JSON"
                invalid_url:
                  summary: Invalid URL format
                  value:
                    error: "Invalid URL: not-a-valid-url"
        '405':
          description: Method not allowed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Method not allowed"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Internal server error"
    options:
      tags:
        - Tracking
      summary: CORS preflight request
      description: Handles CORS preflight requests for cross-origin tracking
      responses:
        '204':
          description: CORS preflight successful
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: "*"
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: "GET, POST, OPTIONS"
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: "Content-Type, Authorization"

  /analytics:
    get:
      tags:
        - Analytics
      summary: Get page analytics data
      description: |
        Retrieves analytics data for page visits with optional filtering by domain and date range.
        Supports pagination to handle large datasets efficiently.
      parameters:
        - name: domain
          in: query
          description: Filter by specific domain
          schema:
            type: string
            example: "example.com"
        - name: start_date
          in: query
          description: Start date for filtering (YYYY-MM-DD format)
          schema:
            type: string
            format: date
            example: "2023-01-01"
        - name: end_date
          in: query
          description: End date for filtering (YYYY-MM-DD format)
          schema:
            type: string
            format: date
            example: "2023-12-31"
        - name: page
          in: query
          description: Page number for pagination
          schema:
            type: integer
            minimum: 1
            default: 1
            example: 1
        - name: limit
          in: query
          description: Number of items per page
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
            example: 20
      responses:
        '200':
          description: Analytics data with pagination
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        url:
                          type: string
                          format: uri
                          example: "https://example.com/about"
                        domain:
                          type: string
                          example: "example.com"
                        path:
                          type: string
                          example: "/about"
                        unique_visits:
                          type: integer
                          minimum: 0
                          example: 98
                        total_visits:
                          type: integer
                          minimum: 0
                          example: 152
                        first_visit:
                          type: string
                          format: date-time
                          example: "2023-01-15 10:30:00"
                        last_visit:
                          type: string
                          format: date-time
                          example: "2023-12-20 16:45:00"
                  pagination:
                    type: object
                    properties:
                      page:
                        type: integer
                        minimum: 1
                        example: 1
                      limit:
                        type: integer
                        minimum: 1
                        maximum: 100
                        example: 20
                      total:
                        type: integer
                        minimum: 0
                        example: 150
                      total_pages:
                        type: integer
                        minimum: 1
                        example: 8
                      has_next_page:
                        type: boolean
                        example: true
                      has_previous_page:
                        type: boolean
                        example: false
              examples:
                success:
                  summary: Successful analytics response
                  value:
                    data:
                      - url: "https://example.com/about"
                        domain: "example.com"
                        path: "/about"
                        unique_visits: 98
                        total_visits: 152
                        first_visit: "2023-01-15 10:30:00"
                        last_visit: "2023-12-20 16:45:00"
                      - url: "https://example.com/contact"
                        domain: "example.com"
                        path: "/contact"
                        unique_visits: 67
                        total_visits: 89
                        first_visit: "2023-02-03 14:20:00"
                        last_visit: "2023-12-19 11:15:00"
                    pagination:
                      page: 1
                      limit: 20
                      total: 150
                      total_pages: 8
                      has_next_page: true
                      has_previous_page: false
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                invalid_page:
                  summary: Invalid page number
                  value:
                    error: "Page must be at least 1"
                invalid_limit:
                  summary: Invalid limit
                  value:
                    error: "Limit must be between 1 and 100"
                invalid_date:
                  summary: Invalid date format
                  value:
                    error: "Invalid date format"
        '405':
          description: Method not allowed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Method not allowed"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Internal server error"
    options:
      tags:
        - Analytics
      summary: CORS preflight request for analytics
      description: Handles CORS preflight requests for cross-origin analytics requests
      responses:
        '204':
          description: CORS preflight successful
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: "*"
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: "GET, OPTIONS"
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: "Content-Type"

  /health:
    get:
      tags:
        - Monitoring
      summary: Health check
      description: |
        Returns the current health status of the API service. 
        Use this endpoint to monitor service availability.
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  timestamp:
                    type: integer
                    description: Unix timestamp
                    example: 1694678400
                  service:
                    type: string
                    example: "yomali-tracker-api"
                  version:
                    type: string
                    example: "1.0.0"
              example:
                status: "healthy"
                timestamp: 1694678400
                service: "yomali-tracker-api"
                version: "1.0.0"
        '500':
          description: Health check failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Health check failed"

tags:
  - name: Tracking
    description: Page visit tracking operations
  - name: Analytics
    description: Analytics and reporting operations  
  - name: Monitoring  
    description: Service health and monitoring endpoints